config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'welcome#index'

  get 'entries', to: 'welcome#approve'

  resources :snacks, except: [:index] do
    get 'approve_it', to: 'snacks#approve_it'
  end

  resources :activities, only: [:create, :new, :destroy] do
    get 'approve_it', to: 'activities#approve_it'
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :description, presence: true
  validates :calories, presence: true
  after_initialize :default_attributes, :if => :new_record?

  scope :approved, -> (b) { where approved: b }

  private
    def default_attributes
      self.approved ||= false
    end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/snack.rb
class Snack < ActiveRecord::Base
  validates :name    , presence: true
  validates :calories, presence: true
  after_initialize :default_attributes, :if => :new_record?

  scope :approved, -> (b) { where approved: b }

  private
    def default_attributes
      self.approved ||= false
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  if false
  # if Rails.env.production?
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]

  respond_to :html

  def index
    @activities = Activity.all
    respond_with(@activities)
  end

  def show
    redirect_to(root_url)
  end

  def new
    @activity = Activity.new
    respond_with(@activity)
  end

  def edit
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.description = @activity.description.capitalize
    @activity.save
    redirect_to root_url, :notice => '¡Gracias por tu aporte!, éste será validado y aprobado por nuestros administradores'
  end

  def update
    @activity.update(activity_params)
    redirect_to(entries_path)
  end

  def destroy
    @activity.destroy
    redirect_to(entries_path)
  end

  def approve_it
    @activity = Activity.find(params[:activity_id])
    @activity.approved = true
    @activity.save
    redirect_to(entries_path)
  end

  private
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:description, :calories, :unit)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_not_approved

  protected
    def authenticate_user!
      if user_signed_in?
        super
      else
        redirect_to root_url, :notice => 'Debes haber iniciado sesión'
      end
    end

  private
    def set_not_approved
      @not_approved = Snack.approved(false).count
      @not_approved += Activity.approved(false).count
    end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  before_action :set_snack, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]

  respond_to :html

  def index
    @snacks = Snack.all
    respond_with(@snacks)
  end

  def show
    if @snack.approved then
      activities = Activity.approved(true)

      @tuples = []
      activities.each do |activity|
        tuple = { activity: activity.description.capitalize,
                  quantity: (@snack.calories / activity.calories).round,
                  unit: activity.unit.downcase
                }
        @tuples.push(tuple)
      end
    else
      redirect_to(root_url)
    end
  end

  def new
    @snack = Snack.new
    respond_with(@snack)
  end

  def edit
  end

  def create
    @snack = Snack.new(snack_params)
    @snack.name = @snack.name.capitalize
    @snack.save
    redirect_to root_url, :notice => '¡Gracias por tu aporte!, éste será validado y aprobado por nuestros administradores'
  end

  def update
    @snack.update(snack_params)
    redirect_to(entries_path)
  end

  def destroy
    @snack.destroy
    redirect_to(entries_path)
  end

  def approve_it
    @snack = Snack.find(params[:snack_id])
    @snack.approved = true
    @snack.save
    redirect_to(entries_path)
  end

  private
    def set_snack
      @snack = Snack.find(params[:id])
    end

    def snack_params
      params.require(:snack).permit(:name, :calories)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:approve]

  def index
    snacks = Snack.approved(true).order(:name)
    activities = Activity.approved(true)
    activities_length = activities.length

    @tuples = []
    snacks.each do |snack|
      activity = activities[rand(activities_length)]
      tuple = { snack: snack,
                name: snack.name,
                calories: snack.calories,
                activity: activity.description.capitalize,
                quantity: (snack.calories / activity.calories).round,
                unit: activity.unit.downcase,
              }
      @tuples.push(tuple)
    end
  end

  def approve
    @activities = Activity.order(:approved)
    @snacks = Snack.order(:approved)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-12 spacer">
      Descripción: <%= f.text_field :description %>, una de éstas (unidades) <%= f.text_field :unit %> quema <%= f.text_field :calories %> calorías
    </div>
  </div>

  <div class="hidden"><%= f.check_box :approved %></div>

  <div class="spacer">
    <h2>Ejemplo</h2>
    Descripción: <b>Nadar</b>, una de éstas (unidades) <b>minutos</b> quema <b>12.5</b> calorías<br>
  </div>

  <div class="actions spacer">
    <%= f.submit %>
  </div>

<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @activity %> |

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Calories</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.description %></td>
        <td><%= activity.calories %></td>
        <td><%= activity.unit %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>Nueva actividad</h1>

<%= render 'form' %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <p class="col-md-3">
      <strong>Description:</strong>
      <%= @activity.description %>
    </p>
</div>
<div class="row">
    <p class="col-md-3">
      <strong>Calories:</strong>
      <%= @activity.calories %>
    </p>
</div>
<div class="row">
    <p class="col-md-3">
      <strong>Unit:</strong>
      <%= @activity.unit %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="header" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="col-md-1"></div>
        <div class="col-md-2">
            <br> <%= link_to 'Inicio', root_url %>
        </div>
        <div class="col-md-3">
            <br> <%= link_to 'Nueva actividad', new_activity_path %>
        </div>
        <div class="col-md-3">
            <br> <%= link_to 'Nueva chuchería', new_snack_path %>
        </div>
        <div class="col-md-1">
            <br>
            <% if user_signed_in? %>
                <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
            <% else %>
                <%= link_to "Sign in", new_user_session_path %>
            <% end %>
        </div>
        <div class="col-md-2">
          <% if user_signed_in? %>
            <% if @not_approved > 0 %>
              <br> <b><%= link_to 'Entradas', entries_path %>*</b>
            <% else %>
              <br> <%= link_to 'Entradas', entries_path %>
            <% end %>
          <% end %>
        </div>
    </div>
</nav>

<div id="under-header"></div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container-fluid">
    <%= yield %>
</div>

</body>
</html>

app/views/snacks/_form.html.erb
<%= form_for(@snack) do |f| %>
  <% if @snack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snack.errors.count, "error") %> prohibited this snack from being saved:</h2>

      <ul>
      <% @snack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Nombre: <%= f.text_field :name %>
  </div>
  <div class="field">
    Calorías: <%= f.number_field :calories %>
  </div>

  <div class="hidden"><%= f.check_box :approved %></div>

  <div class="spacer">
    <h2>Ejemplo</h2>
    Nombre: <b>Snickers</b><br>
    Calorías: <b>181</b><br>
  </div>

  <div class="actions spacer">
    <%= f.submit %>
  </div>
<% end %>

app/views/snacks/edit.html.erb
<h1>Editing snack</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @snack %> |

app/views/snacks/index.html.erb
<h1>Listing snacks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Calories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snacks.each do |snack| %>
      <tr>
        <td><%= link_to snack.name, snack %></td>
        <td><%= snack.calories %></td>
        <td><%= link_to 'Modificar', edit_snack_path(snack) %></td>
        <td><%= link_to 'Eliminar', snack, method: :delete, data: { confirm: '¿Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snack', new_snack_path %>

app/views/snacks/new.html.erb
<h1>Nueva chucería</h1>

<%= render 'form' %>

app/views/snacks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <p class="col-md-5">
    <h2 class="text-center">
        <%= @snack.name %>
    </h2>
  </p>
</div>
<div class="row">
  <p class="col-md-5">
    <h2 class="text-center">
        <%= @snack.calories %> Calorías
    </h2>
  </p>
</div>

<table class="table">
    <thead>
        <tr class="row">
            <th class="col-md-3">Equivalente a</th>
        </tr>
    </thead>
    <tbody>
        <% @tuples.each do |tuple| %>
            <tr class="row">
                <td class="col-md-3"><%= tuple[:activity] %> <%= tuple[:quantity] %> <%= tuple[:unit] %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/welcome/approve.html.erb
<table class="table table-striped">
    <h3>Actividades</h3>
    <thead>
        <tr>
          <th>Descripción</th>
          <th>Calorías</th>
          <th>Unidades</th>
          <th colspan="2"></th>
        </tr>
    </thead>

    <tbody>
        <% @activities.each do |activity| %>
          <tr>
            <td><%= activity.description %></td>
            <td><%= activity.calories %></td>
            <td><%= activity.unit %></td>
            <% if not activity.approved %>
              <td><%= link_to 'Aprobar', '/activities/' + activity.id.to_s + '/approve_it' %></td>
            <% else %>
              <td></td>
            <% end %>
            <td><%= link_to 'Eliminar', activity, method: :delete, data: { confirm: '¿Seguro?' } %></td>
          </tr>
        <% end %>
    </tbody>
</table>

<table class="table table-striped">
    <h3>Chucherías</h3>
    <thead>
        <tr>
          <th>Nombre</th>
          <th>Calorías</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @snacks.each do |snack| %>
          <tr>
            <td><%= snack.name %></td>
            <td><%= snack.calories %></td>
            <% if not snack.approved %>
              <td><%= link_to 'Aprobar', '/snacks/' + snack.id.to_s + '/approve_it' %></td>
            <% else %>
              <td></td>
            <% end %>
            <td><%= link_to 'Eliminar', snack, method: :delete, data: { confirm: '¿Seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    <thead></thead>
</table>

app/views/welcome/index.html.erb
<table class="table table-striped table-hover">
    <thead>
        <tr class="row">
            <th class="col-md-3">Chuchería</th>
            <th class="col-md-3">Calorías</th>
            <th class="col-md-3">Actividad</th>
        </tr>
    </thead>

    <tbody>
        <% @tuples.each do |tuple| %>
            <tr class="row">
                <td class="col-md-3"><%= link_to tuple[:name], tuple[:snack] %></td>
                <td class="col-md-3"><%= tuple[:calories] %></td>
                <td class="col-md-3"><%= tuple[:activity] %> <%= tuple[:quantity] %> <%= tuple[:unit] %></td>
            </tr>
        <% end %>
    </tbody>
</table>